const SB=window.SUPABASE_CONFIG||{};
const hasSupabase=!!(SB.url&&SB.anonKey&&!SB.url.includes('YOUR_')&&!SB.anonKey.includes('YOUR_'));
const db=hasSupabase?window.supabase.createClient(SB.url,SB.anonKey):null;
const state={week:0,startDate:localStorage.getItem('studyStartDate')||'2026-08-31',taskState:JSON.parse(localStorage.getItem('taskState')||'{}'),notes:localStorage.getItem('appNotes')||'',user:null,syncing:false};
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x},fmt=d=>d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}),dateKey=d=>d.toISOString().slice(0,10);
const lessonForWeek=w=>w<10?CURRICULUM.lessons[w]:null;
const consolidationLessons=w=>w===10?CURRICULUM.lessons.slice(0,5):CURRICULUM.lessons.slice(5,10);
function pageFor(l,key){for(const b of ['workbook2','workbook1'])if(l[b]?.[key]!=null)return{book:b==='workbook2'?'Workbook 2':'Workbook 1',page:l[b][key]};return null}
function defFor(key){return TASK_TYPES.find(x=>x.key===key)}
function makeTask(l,w,d,key){const def=defFor(key),ref=pageFor(l,key);if(!def||!ref)return null;return{id:`b2-w${w+1}-d${d+1}-${key}`,lesson:l.n,key,title:`${def.label} · p.${ref.page}`,book:def.book,page:ref.page,duration:def.duration,desc:def.desc}}
function weeklyTasks(w,d){
 if(w>=10)return consolidationTasks(w,d);
 const l=lessonForWeek(w), keys=[['vocab','kanji'],['particle','grammar1'],['comp1','reading'],['grammar2','comp2'],['listening','writing'],['review'],[]][d];
 const out=keys.map(k=>makeTask(l,w,d,k)).filter(Boolean);
 if(d===5)out.push({id:`b2-w${w+1}-d6-consolidation`,lesson:l.n,key:'consolidation',title:'Lesson consolidation + catch-up',duration:'30–45 min',book:'Your notes',desc:'Return to anything marked shaky or weak. Re-test it without notes, then update mastery.'});
 if(d===6)out.push({id:`b2-w${w+1}-d7-mastery`,lesson:l.n,key:'mastery',title:`Mastery check · Lesson ${l.n}`,duration:'20–30 min',book:'Dashboard',desc:'Check each lesson area. Can you recognise it, understand it and produce it without looking? Mark each component accordingly.'});
 return out;
}
function consolidationTasks(w,d){
 const ls=consolidationLessons(w),label=w===10?'Lessons 11–15':'Lessons 16–20';
 if(d===6)return[{id:`b2-w${w+1}-d7-mastery`,key:'mastery',title:`Mastery check · ${label}`,duration:'30–45 min',book:'Dashboard',desc:'Review recorded mastery across this block. Re-test every shaky or weak component and update your status.'}];
 const l=ls[d], key=['vocab','particle','grammar1','grammar2','listening','reading','writing'][d];
 if(!l)return[{id:`b2-w${w+1}-d${d+1}-catchup`,key:'catchup',title:`Consolidation · ${label}`,duration:'30–45 min',book:'Your notes',desc:'Use this session for unfinished work and the weakest remaining areas.'}];
 const t=makeTask(l,w,d,key);return t?[{...t,title:`L${l.n} · ${t.title}`,desc:t.desc+' This is a consolidation pass: prioritise anything previously marked shaky or weak.'}]:[{id:`b2-w${w+1}-d${d+1}-targeted`,key:'targeted',title:`L${l.n} · targeted review`,duration:'30–45 min',book:'Your notes',desc:'Review the weakest remaining component from this lesson and update its mastery.'}];
}
function habits(w,d){return OPTIONAL_TASKS.map(x=>({id:`habit-w${w+1}-d${d+1}-${x.key}`,key:x.key,title:x.label,duration:x.duration,book:'Habit',desc:x.desc,habit:true}))}
function ts(id){return state.taskState[id]||{completed:false,mastery:'not_started',confidence:null,notes:'',completed_at:null}}
function saveLocal(){localStorage.setItem('taskState',JSON.stringify(state.taskState));localStorage.setItem('appNotes',state.notes);localStorage.setItem('studyStartDate',state.startDate)}
async function cloudSave(id){if(!db||!state.user)return;const t=ts(id);const{error}=await db.from('task_state').upsert({user_id:state.user.id,task_id:id,completed:t.completed,completed_at:t.completed_at,mastery:t.mastery,confidence:t.confidence,notes:t.notes},{onConflict:'user_id,task_id'});if(error)toast('Cloud save failed; local copy is safe.')}
function setTask(id,p){state.taskState[id]={...ts(id),...p};saveLocal();render();cloudSave(id)}
function toggle(id){const t=ts(id);setTask(id,{completed:!t.completed,completed_at:!t.completed?new Date().toISOString():null})}
function allTasks(w){return Array.from({length:7},(_,d)=>weeklyTasks(w,d)).flat()}
function progress(w){const a=allTasks(w);return{done:a.filter(t=>ts(t.id).completed).length,total:a.length}}
function weekDates(w){const s=new Date(state.startDate+'T00:00:00');return Array.from({length:7},(_,i)=>addDays(s,w*7+i))}
function render(){renderHeader();renderTabs();renderWeek();$('#globalNotes').value=state.notes;renderStatus()}
function renderHeader(){const l=lessonForWeek(state.week),p=progress(state.week),ds=weekDates(state.week);$('#weekLabel').textContent=`Week ${state.week+1}`;$('#lessonLabel').textContent=l?`Lesson ${l.n}: ${l.title}`:(state.week===10?'Lessons 11–15: consolidation':'Lessons 16–20: consolidation');$('#lessonEnglish').textContent=l?l.english:'Re-test, repair and consolidate the Beginning II course.';$('#dateRange').textContent=`${fmt(ds[0])} – ${fmt(ds[6])}`;$('#progressText').textContent=`${p.done}/${p.total} core tasks complete` ;$('#progressBar').style.width=(p.total?p.done/p.total*100:0)+'%'}
function renderTabs(){$('#weekTabs').innerHTML=Array.from({length:12},(_,i)=>`<button class="weektab ${i===state.week?'active':''}" data-week="${i}">W${i+1}</button>`).join('');$('#weekTabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.week=+b.dataset.week;render();scrollTo({top:0,behavior:'smooth'})})}
function card(t){const s=ts(t.id);return`<article class="task ${s.completed?'done':''}" data-task="${esc(t.id)}"><input type="checkbox" data-check="${esc(t.id)}" ${s.completed?'checked':''}><div class="taskmain"><div class="tasktitle">${esc(t.title)}</div><div class="taskmeta">${esc(t.book)}${t.page?` · p.${t.page}`:''} · ${esc(t.duration)}</div><div class="taskhint">Tap for instructions, mastery and notes</div></div><span class="status-dot ${s.mastery}"></span></article>`}
function renderWeek(){const ds=weekDates(state.week);$('#week').innerHTML=ds.map((date,d)=>{const core=weeklyTasks(state.week,d),hs=habits(state.week,d),today=dateKey(date)===dateKey(new Date());return`<section class="day ${today?'today':''}"><div class="dayhead"><div><div class="eyebrow">${today?'TODAY · ':''}${date.toLocaleDateString(undefined,{weekday:'long'})}</div><h2>${fmt(date)}</h2></div><span class="daycount">${core.filter(t=>ts(t.id).completed).length}/${core.length}</span></div>${core.length?`<div class="tasklist">${core.map(card).join('')}</div>`:''}<details class="habits"><summary>Daily habits <span>WaniKani · Migaku · shadowing · reading</span></summary><div class="habitlist">${hs.map(card).join('')}</div></details></section>`}).join('');$('#week').querySelectorAll('[data-task]').forEach(e=>e.onclick=x=>{if(x.target.matches('input'))return;openTask(e.dataset.task)});$('#week').querySelectorAll('[data-check]').forEach(e=>e.onchange=()=>toggle(e.dataset.check))}
function openTask(id){const t=[...allTasks(state.week),...habits(state.week,0),...habits(state.week,1),...habits(state.week,2),...habits(state.week,3),...habits(state.week,4),...habits(state.week,5),...habits(state.week,6)].find(x=>x.id===id);if(!t)return;const s=ts(id);$('#modalTitle').textContent=t.title;$('#modalSub').textContent=`${t.lesson?`TOBIRA Beginning Japanese II · Lesson ${t.lesson}`:'Daily habit'} · ${t.book}${t.page?` · p.${t.page}`:''}`;$('#modalDesc').innerHTML=`<p>${esc(t.desc)}</p>${t.lesson?'<p><strong>Study rule:</strong> Work through this section fully. If you already know it, do a small representative check and mark the skill mastered instead of grinding repetitive questions.</p>':''}`;$('#modalDone').checked=s.completed;$('#modalDone').onchange=()=>toggle(id);$('#mastery').value=s.mastery;$('#mastery').onchange=e=>setTask(id,{mastery:e.target.value});$('#confidence').value=s.confidence||'';$('#confidence').onchange=e=>setTask(id,{confidence:e.target.value?+e.target.value:null});$('#taskNotes').value=s.notes||'';$('#taskNotes').oninput=e=>{state.taskState[id]={...ts(id),notes:e.target.value};saveLocal();cloudSave(id)};$('#modal').showModal()}
async function loadCloud(){if(!db||!state.user)return;const{data,error}=await db.from('task_state').select('*').eq('user_id',state.user.id);if(!error)data.forEach(r=>state.taskState[r.task_id]={completed:r.completed,mastery:r.mastery,confidence:r.confidence,notes:r.notes,completed_at:r.completed_at});const{data:n}=await db.from('app_notes').select('notes').eq('user_id',state.user.id).maybeSingle();if(n)state.notes=n.notes||'';const{data:p}=await db.from('user_preferences').select('start_date').eq('user_id',state.user.id).maybeSingle();if(p?.start_date)state.startDate=p.start_date;saveLocal();render()}
async function initAuth(){if(!db){renderStatus();return}const{data}=await db.auth.getSession();state.user=data.session?.user||null;renderStatus();if(state.user)await loadCloud();db.auth.onAuthStateChange((_e,s)=>{state.user=s?.user||null;renderStatus();if(state.user)loadCloud()})}
function renderStatus(){$('#syncStatus').textContent=state.syncing?'Syncing…':state.user?'☁ Synced account':hasSupabase?'Configured · sign in':'Local mode';$('#userLabel').textContent=state.user?.email||''}
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
$('#prevWeek').onclick=()=>{state.week=Math.max(0,state.week-1);render()};$('#nextWeek').onclick=()=>{state.week=Math.min(11,state.week+1);render()};$('#saveGlobalNotes').onclick=async()=>{state.notes=$('#globalNotes').value;saveLocal();if(db&&state.user)await db.from('app_notes').upsert({user_id:state.user.id,notes:state.notes},{onConflict:'user_id'});toast('Notes saved')};$('#startDate').value=state.startDate;$('#startDate').onchange=async e=>{state.startDate=e.target.value||'2026-08-31';saveLocal();if(db&&state.user)await db.from('user_preferences').upsert({user_id:state.user.id,start_date:state.startDate},{onConflict:'user_id'});render()};$('#openLogin').onclick=()=>$('#authDialog').showModal();$('#closeLogin').onclick=()=>$('#authDialog').close();$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!db){toast('Add Supabase values to supabase-config.js first.');return}const{error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)toast(error.message);else{$('#authDialog').close();toast('Signed in')}};$('#logout').onclick=async()=>{if(db)await db.auth.signOut();state.user=null;renderStatus()};
render();initAuth();
