const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const routerSource = fs.readFileSync(path.join(root, 'router.js'), 'utf8');
const styleSource = fs.readFileSync(path.join(root, 'styles.css'), 'utf8');
const context = {state:{taskState:{},lessonVideos:[]},console,URL,document:{baseURI:'https://hub.test/',addEventListener(){}}};
context.window = context;
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(root, 'curriculum.js'), 'utf8'), context);
vm.runInContext(fs.readFileSync(path.join(root, 'audio-map.js'), 'utf8'), context);
context.AUDIO_LIBRARY=context.LESSON_AUDIO;
vm.runInContext(fs.readFileSync(path.join(root, 'ninjal.js'), 'utf8'), context);
// Exercise the real pure planning/rendering functions without booting auth.
for (const name of ['defFor','pageFor','makeTask','lessonTasks','weeklyTasks','ts','taskStudyChecklist','lessonGuideSteps','flattenGuideSteps','guideSectionProgress','nextGuideActivityId','guideAudioMarkup','taskGoalFor','guideTaskWorkspaceMarkup','guideStepMarkup','lessonGuideMarkup','scrollToGuideActivity']) {
  const start=source.indexOf(`function ${name}(`);
  assert.ok(start>=0, `Missing ${name}`);
  const end=source.indexOf('\nfunction ',start+1);
  vm.runInContext(source.slice(start,end<0?undefined:end), context);
}
vm.runInContext(`
  function lessonForWeek(w){return CURRICULUM.lessons[w];}
  function consolidationTasks(w,d){return ['unchanged-consolidation',w,d];}
  function lessonVideosByType(l,type){return state.lessonVideos.filter(v=>v.lesson===l.n&&v.video_type===type);}
  function grammarPageFromVideos(rows,fallback){return 'pp.'+fallback;}
  function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function guideVideoLinks(videos){return videos.map(v=>esc(v.title)).join('');}
  function taskSeconds(id){return (state.sessions||[]).filter(session=>session.task_id===id).reduce((total,session)=>total+session.duration_seconds,0);}
  function fmtDuration(totalSec){const totalMin=Math.round((totalSec||0)/60),hours=Math.floor(totalMin/60),minutes=totalMin%60;return hours?hours+'h '+minutes+'m':minutes+'m';}
`,context);
const plain = value => JSON.parse(JSON.stringify(value));
for (const lesson of context.CURRICULUM.lessons) {
  const steps=context.lessonGuideSteps(lesson);
  const flat=context.flattenGuideSteps(steps);
  const ids=flat.map(s=>s.id);
  assert.equal(new Set(ids).size,ids.length,'No duplicate activities');
  assert.deepEqual(plain(steps.slice(0,4).map(s=>s.id)),['guide-goals','textbook_conversation','textbook_vocab_pictures','textbook_vocab'].map(k=>`b2-l${lesson.n}-${k}`));
  assert.equal(context.pageFor(lesson,'textbook_conversation').page,lesson.textbook.pages.conversation);
  assert.equal(context.pageFor(lesson,'textbook_vocab').page,lesson.textbook.pages.vocab);
  assert.equal(context.pageFor(lesson,'guide-goals').page,lesson.textbook.start);
  const scheduled=Array.from({length:7},(_,d)=>context.weeklyTasks(lesson.n-11,d)).flat();
  assert.deepEqual(plain(scheduled.map(t=>t.id)),plain(flat.filter(s=>scheduled.some(t=>t.id===s.id)).map(s=>s.id)),'Plan follows lesson order');
  for(const task of context.lessonTasks(lesson)) assert.ok(ids.includes(task.id),`Missing task ${task.id}`);
  const grammar=steps.find(s=>s.id.endsWith('-textbook_grammar'));
  const shadowing=steps.find(s=>s.id.endsWith('-textbook_conversation_shadowing'));
  assert.equal(steps.indexOf(shadowing),steps.indexOf(grammar)+1,'Shadowing follows grammar and its supporting practice');
  assert.ok(steps[steps.indexOf(shadowing)+1].id.endsWith('-textbook_talk'),'Shadowing prepares for speaking');
  assert.equal(shadowing.audio,'conversation');
  const audioHTML=context.guideAudioMarkup(lesson,shadowing);
  assert.ok(audioHTML.includes('data-guide-audio="conversation"'));
  assert.ok(audioHTML.includes('<audio'));
  assert.ok(audioHTML.includes('value="0.75"'));
  assert.ok(audioHTML.includes('data-audio-command="back"'));
  assert.ok(!audioHTML.includes('Book closed first'),'Second-pass instructions suit shadowing');
  for(const track of context.AUDIO_LIBRARY.lessons[lesson.n].groups.conversation) assert.ok(audioHTML.includes(context.esc(track.title)));
  assert.equal(shadowing.page,`p.${lesson.textbook.pages.conversation}`);
  assert.equal(context.pageFor(lesson,'textbook_conversation_shadowing').page,lesson.textbook.pages.conversation);
  const shadowTask=context.weeklyTasks(lesson.n-11,4).find(t=>t.key==='textbook_conversation_shadowing');
  assert.equal(shadowTask.id,shadowing.id,'Plan day 5 and lesson share one progress record');
  assert.equal(shadowTask.duration,'15–20 min');
  assert.equal(scheduled.filter(t=>t.id===shadowing.id).length,1);
  assert.ok(shadowing.checklist[0].includes(`Lesson ${lesson.n}`));
  assert.ok(shadowing.checklist.some(line=>line.includes('without pausing')));
  assert.ok(shadowing.checklist.some(line=>line.includes('Mark complete')));
  assert.equal(grammar.support.filter(s=>s.id.includes('-guide-grammar-')).length,lesson.textbook.grammar.length);
  assert.ok(steps.find(s=>s.id.endsWith('-textbook_vocab')).support.some(s=>s.id.endsWith('-vocab')));
  const html=context.lessonGuideMarkup(lesson);
  assert.equal(html.split('data-ninjal-label=').length-1,lesson.textbook.grammar.length,'One source panel per grammar point; none on vocabulary or shadowing');
  for(const id of ids) assert.equal(html.split(`id="guide-${id}"`).length-1,1,`Unique rendered target ${id}`);
}
assert.deepEqual(plain(context.weeklyTasks(10,2)),['unchanged-consolidation',10,2]);
const l=context.CURRICULUM.lessons[0];
context.state.lessonVideos=[{lesson:11,video_type:'dialogue',title:'Dialogue'},{lesson:11,video_type:'vocabulary',title:'Vocabulary'},{lesson:11,video_type:'grammar',grammar_index:'1a',title:'Grammar 1'}];
const steps=context.lessonGuideSteps(l);
context.state.sessions=[{task_id:'b2-l11-textbook_conversation',duration_seconds:4500}];
assert.ok(steps[1].support.some(s=>s.id==='b2-l11-guide-video-dialogue'));
assert.ok(steps[3].support.some(s=>s.id==='b2-l11-guide-video-vocabulary'));
const conversationWorkspace=context.guideTaskWorkspaceMarkup(l,steps[1],1,steps,true,steps[2].id);
assert.ok(conversationWorkspace.includes('data-guide-pomodoro="b2-l11-textbook_conversation"'),'Guided task timer uses the exact lesson task ID');
assert.ok(conversationWorkspace.includes('Studied: 1h 15m'),'Guided task shows its existing accumulated focus time');
assert.ok(conversationWorkspace.includes('<label>Notes<textarea'),'Guided task retains its notes field');
assert.ok(conversationWorkspace.includes('data-guide-check="b2-l11-textbook_conversation"'),'Completion stays beside notes, study time and Pomodoro');
assert.ok(!/Mastery|Confidence|data-guide-mastery|data-guide-confidence/.test(conversationWorkspace),'Guided task has no rating workflow');
const conversationTracks=context.AUDIO_LIBRARY.lessons[11].groups.conversation;
context.state.lessonMedia={taskId:'b2-l11-textbook_conversation',lesson:11,mediaType:'audio',category:'conversation',open:true,selectedTrack:conversationTracks[1].path,currentTime:12,wasPlaying:false};
const restoredAudio=context.guideAudioMarkup(l,steps[1]);
assert.ok(restoredAudio.includes('data-guide-task-id="b2-l11-textbook_conversation"'));
assert.ok(restoredAudio.includes('aria-expanded="true"'),'Open inline media is reconstructed as open');
assert.ok(!/data-guide-audio-box="conversation"[^>]*hidden/.test(restoredAudio),'The restored audio panel is not collapsed');
assert.match(context.guideTaskWorkspaceMarkup(l,steps[1],1,steps,false,steps[2].id),/^<details class="guide-task-workspace"[^>]* open>/,'Media state keeps its parent task workspace open');
assert.match(source,/document\.addEventListener\('visibilitychange',captureActiveLessonMedia\)/,'Tab visibility captures the active track and position without rendering');
assert.match(source,/tracks\.findIndex\(track=>track\.path===state\.lessonMedia\.selectedTrack\)/,'Inline audio restores the selected task track');
const saved={completed:true,notes:'Existing note',mastery:'studying',confidence:3};
context.state.taskState['b2-l11-textbook_vocab']=saved;
assert.equal(context.ts('b2-l11-textbook_vocab'),saved);
assert.ok(!/Mastery|Confidence|studying/.test(context.guideTaskWorkspaceMarkup(l,steps[2],2,steps,false,steps[3].id)),'Historical rating values do not affect the lesson workspace');
assert.equal(context.ts('b2-l11-textbook_vocab_pictures').completed,false,'Do not invent completion for split vocabulary');
context.state.taskState['b2-l11-textbook_conversation']=saved;
assert.equal(context.ts('b2-l11-textbook_conversation_shadowing').completed,false,'First-pass completion does not complete shadowing');
assert.equal(context.ts('b2-l11-textbook_conversation'),saved,'Existing conversation record is untouched');
const ordered=context.flattenGuideSteps(steps),nestedIndex=ordered.findIndex(step=>step.id.includes('-guide-grammar-'));
for(const step of ordered) context.state.taskState[step.id]={completed:ordered.indexOf(step)<nestedIndex};
assert.equal(context.nextGuideActivityId(l,ordered[nestedIndex].id,true),ordered[nestedIndex+1].id,'Completing a nested grammar activity advances in flattened curriculum order');
for(const step of ordered) context.state.taskState[step.id]={completed:true};
context.state.taskState[ordered[0].id]={completed:false};context.state.taskState[ordered.at(-1).id]={completed:false};
assert.equal(context.nextGuideActivityId(l,ordered.at(-1).id,true),ordered[0].id,'After the last activity, Continue returns to any earlier unfinished work');
const sectionsWithSupport=steps.filter(step=>step.support?.length).slice(0,2);
assert.equal(sectionsWithSupport.length,2,'Acceptance coverage includes more than one section with supporting work');
for(const section of sectionsWithSupport){
  for(const activity of context.flattenGuideSteps([section])) context.state.taskState[activity.id]={completed:false};
  context.state.taskState[section.id]={completed:true};
  const support=section.support[0], progress=context.guideSectionProgress(section);
  assert.equal(progress.mainComplete,true,'The individual main task remains complete');
  assert.equal(progress.complete,false,'A completed main task does not complete its section');
  assert.equal(progress.done,1);assert.ok(progress.remaining>0);
  const partial=context.guideStepMarkup(l,section,steps.indexOf(section),steps,support.id);
  assert.ok(!/^<article class="[^"]*\bdone\b/.test(partial),'The outer section does not receive completed styling');
  assert.match(partial,/supporting tasks? remaining/,'Collapsed section summary exposes unfinished supporting work');
  assert.match(partial,/data-guide-check="[^"]+" checked><span>Completed<\/span>/,'The main task still displays its own completed state');
  for(const activity of context.flattenGuideSteps([section])) context.state.taskState[activity.id]={completed:true};
  const complete=context.guideStepMarkup(l,section,steps.indexOf(section),steps,null);
  assert.match(complete,/^<article class="[^"]*\bdone\b/,'Only a fully completed section receives completed styling');
  assert.ok(complete.includes('✓ Section complete'));
}
for(const activity of ordered) context.state.taskState[activity.id]={completed:true};
const kanji=steps.find(step=>step.id.endsWith('-textbook_kanji'));
assert.ok(kanji?.support.length,'Kanji has independently tracked supporting practice');
const kanjiSupport=kanji.support[0];
context.state.taskState[kanjiSupport.id]={completed:false};
assert.ok(context.lessonGuideMarkup(l).includes(`data-guide-scroll="${kanjiSupport.id}"`),'Continue targets unfinished supporting practice when its main task is complete');
for(const step of context.flattenGuideSteps(steps)) context.state.taskState[step.id]={completed:true};
delete context.state.taskState['b2-l11-textbook_conversation_shadowing'];
assert.ok(context.lessonGuideMarkup(l).includes('data-guide-scroll="b2-l11-textbook_conversation_shadowing"'),'Previously completed lessons continue at the new shadowing step');
context.state.taskState['b2-l11-textbook_conversation_shadowing']={completed:true,notes:'Shadowed track 1'};
context.state.taskState['b2-l11-vocab']={completed:false,notes:'Workbook note'};
const html=context.lessonGuideMarkup(l);
assert.ok(html.includes('data-guide-scroll="b2-l11-vocab"'),'Continue finds unfinished nested practice');
assert.ok(!html.includes('Lesson path complete.'));
assert.ok(html.includes('Workbook note'));
assert.equal(context.weekPlan(0).days[0].focus,'Goals, conversation and picture vocabulary');
assert.equal(context.weekPlan(0).days[4].focus,'Conversation shadowing and speaking');
const ancestor={tagName:'DETAILS',open:false,parentElement:null};
const workspace={open:false};
let scrolled=false;
context.document={getElementById:id=>id==='guide-nested'?{parentElement:ancestor,querySelector:()=>workspace,scrollIntoView:()=>{scrolled=true;}}:null};
context.scrollToGuideActivity('nested');
assert.ok(ancestor.open&&workspace.open&&scrolled,'Nested navigation reveals ancestors and workspace');
context.scrollToGuideActivity('missing');
const timerContext={state:{pomoOpen:false,pomodoro:{status:'running',mode:'work',remaining:1200,taskId:'other-task'}},localStorage:{setItem(){}},renderPomodoro(){},renderNav(){},findTaskById(){return {title:'Another task'};},pomodoroDuration(){return 1500;}};
timerContext.toast=message=>{timerContext.message=message;};timerContext.startPomodoro=taskId=>{timerContext.started=taskId;timerContext.state.pomodoro.status='running';timerContext.state.pomodoro.taskId=taskId;};
timerContext.window=timerContext;vm.createContext(timerContext);
const startTaskStart=source.indexOf('function startTaskPomodoro('),startTaskEnd=source.indexOf('\nfunction pausePomodoro',startTaskStart);
vm.runInContext(source.slice(startTaskStart,startTaskEnd),timerContext);
assert.equal(timerContext.startTaskPomodoro('new-task'),false,'A running timer is not silently reassigned');
assert.equal(timerContext.state.pomodoro.taskId,'other-task');assert.match(timerContext.message,/Another task/);
timerContext.state.pomodoro={status:'idle',mode:'short',remaining:300,taskId:'other-task',endAt:null,startedAt:null};
assert.equal(timerContext.startTaskPomodoro('new-task'),true);assert.equal(timerContext.state.pomodoro.mode,'work');assert.equal(timerContext.started,'new-task','Starting from a lesson begins work linked to that task');
timerContext.logs=[];timerContext.syncRemaining=()=>{};timerContext.savePomodoro=()=>{};timerContext.logSession=(...args)=>timerContext.logs.push(args);
const stopTaskStart=source.indexOf('function stopPomodoroForTaskCompletion('),stopTaskEnd=source.indexOf('\nasync function cloudLogSession',stopTaskStart);
vm.runInContext(source.slice(stopTaskStart,stopTaskEnd),timerContext);
timerContext.state.pomodoro={status:'running',mode:'work',remaining:1440,taskId:'conversation',startedAt:'start',endAt:Date.now()+1440000};
assert.equal(timerContext.stopPomodoroForTaskCompletion('conversation'),true);assert.equal(timerContext.logs[0][0],'conversation');assert.equal(timerContext.logs[0][1],60);assert.equal(timerContext.state.pomodoro.status,'idle');assert.equal(timerContext.state.pomodoro.taskId,null,'Completed task clears its timer link');assert.equal(timerContext.state.pomodoro.mode,'work','Task completion does not start a break');
timerContext.logs=[];timerContext.state.pomodoro={status:'paused',mode:'work',remaining:1380,taskId:'conversation',startedAt:'start',endAt:null};
timerContext.stopPomodoroForTaskCompletion('conversation');assert.equal(timerContext.logs[0][1],120,'Paused elapsed work is logged');assert.equal(timerContext.state.pomodoro.taskId,null);
timerContext.logs=[];timerContext.state.pomodoro={status:'running',mode:'work',remaining:1400,taskId:'different-task',startedAt:'start',endAt:null};
assert.equal(timerContext.stopPomodoroForTaskCompletion('conversation'),false);assert.equal(timerContext.state.pomodoro.taskId,'different-task');assert.equal(timerContext.logs.length,0,'Another task timer is untouched');
timerContext.state.taskState={conversation:{completed:false}};timerContext.ts=id=>timerContext.state.taskState[id]||{completed:false};timerContext.setTask=(id,patch)=>{timerContext.state.taskState[id]={...timerContext.ts(id),...patch};};
const toggleStart=source.indexOf('function toggle('),toggleEnd=source.indexOf('\nfunction weekDates',toggleStart);vm.runInContext(source.slice(toggleStart,toggleEnd),timerContext);
timerContext.state.pomodoro={status:'running',mode:'work',remaining:1470,taskId:'conversation',startedAt:'start',endAt:null};timerContext.logs=[];
timerContext.toggle('conversation');assert.equal(timerContext.state.taskState.conversation.completed,true);assert.equal(timerContext.state.pomodoro.taskId,null,'The shared completion path settles its matching Pomodoro');
assert.ok(!source.includes("$('#mastery')"),'Task modal does not read or write mastery');
assert.ok(!source.includes("$('#confidence')"),'Task modal does not read or write confidence');
assert.ok(!source.includes('p.mastered'),'Lesson progress does not derive a mastered total');
assert.ok(!source.includes('st.mastery'),'Dashboard and review logic do not depend on mastery');
assert.ok(!source.includes('function reviewItems('),'Learning Hub has no generic task review scheduler');
assert.ok(!source.includes('Review queue'),'Dashboard has no generic task review panel');
assert.ok(!source.includes('data-review-task'),'Completed tasks are not resurfaced by a manual review workflow');
assert.ok(source.includes('textbook_conversation_shadowing'),'Curriculum-defined conversation replay/shadowing remains');
assert.ok(source.includes('Programme consolidation'),'Curriculum-defined consolidation remains');
assert.match(source,/data-guide-workspace="\$\{esc\(step\.id\)\}"/,'Task workspaces expose stable activity identity');
assert.match(source,/window\.JLHRouter\?\.guideOpened\(nextId\)/,'Completion keeps the routed current task aligned with the next activity');
assert.match(routerSource,/state\.activeGuideTaskId=r\.step/,'Browser history restores the routed Guided Lesson workspace');
assert.match(styleSource,/guide-task-notes,.guide-audio-select,.guide-inline-controls select \{ font-size:16px; \}/,'Phone-sized editable lesson controls prevent iOS focus zoom');
assert.match(source,/upsert\(\{user_id:state\.user\.id,task_id:id,completed:t\.completed,completed_at:t\.completed_at,notes:t\.notes\}/,'Cloud task writes contain only active workflow fields');
assert.match(source,/state\.taskState\[r\.task_id\]=\{completed:r\.completed,notes:r\.notes,completed_at:r\.completed_at\}/,'Cloud hydration ignores historical rating columns');
console.log('PASS: Lessons 11–20 ordering, exact page lookup, Plan parity, nested resources, stable records, no duplicate targets, consolidation unchanged.');
