const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const nodes=new Map();
function node(){return {value:'',innerHTML:'',disabled:false,isConnected:true,handlers:{},addEventListener(k,fn){this.handlers[k]=fn;}};}
for(const id of ['#repoImportJson','#repoImportPreview','#repoRunImport'])nodes.set(id,node());
const messages=[];
let conflictInputs=[];
const context={console,TextEncoder,localStorage:{getItem:()=>null},state:{user:{id:'user'},view:'repository'},
  $:s=>nodes.get(s)||null,document:{querySelectorAll:s=>s==='[data-repo-conflict]'?conflictInputs:[]},toast:x=>messages.push(x),
  esc:x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))};
context.window=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../repository.js'),'utf8'),context);
const state=vm.runInContext('repositoryState',context);
const explanation={label:'〜と思う',sense:'opinion',meaning:'I think',formation:['Plain clause + と思う'],explanation:'Expresses a thought.',examples:[{japanese:'いいと思う。',japanese_furigana:'いいと[思|おも]う。',english:'I think it is good.'}]};
const entry={japanese:'いいと思う。',japanese_furigana:'いいと[思|おも]う。',english:'I think it is good.',grammar_points:['〜と思う'],grammar_explanations:[explanation]};
const copy=x=>JSON.parse(JSON.stringify(x));
const plan=x=>context.repositoryPlanImport(x);
const first=plan(entry);
assert.equal(first.items[0].guides.length,1);assert.equal(first.conflicts.length,0);assert.equal(first.warnings.length,0);
assert.equal(plan([entry,entry]).items[1].guides[0].reused,true);
const saved={...first.items[0].guides[0],id:'guide1',grammar_key:'と思う'};
state.grammarGuides=[saved];
assert.equal(plan(entry).items[0].guides[0].reused,true);
const changed=copy(entry);changed.grammar_explanations[0].meaning='Different content';
assert.equal(plan(changed).conflicts.length,1);
const sense=copy(changed);sense.grammar_explanations[0].sense='another-meaning';
assert.equal(plan(sense).conflicts.length,0);
state.grammarGuides=[];
assert.equal(plan([entry,changed]).conflicts[0].saved,false);
assert.equal(plan({japanese:'日本語',grammar:['〜と思う']}).warnings.length,2,'Missing readings and ignored old grammar alias are visible');
assert.throws(()=>plan({...entry,japanese_furigana:'違う'}),/Furigana/);
assert.throws(()=>plan({...entry,grammar_explanations:{}}),/array/);
assert.throws(()=>plan({...entry,grammar_explanations:[{...explanation,sense:''}]}),/sense/);
assert.throws(()=>plan({...entry,grammar_explanations:[{...explanation,label:'〜ようと思う'}]}),/grammar_points/);
assert.throws(()=>plan({...entry,grammar_explanations:[{...explanation,examples:[{japanese:'私',japanese_furigana:'[君|きみ]',english:'I'}]}]}),/furigana/);
assert.throws(()=>plan({...entry,grammar_explanations:[{...explanation,verified:true}]}),/unknown/);
assert.throws(()=>plan([entry,null]),/Entry 2/);
assert.throws(()=>plan(Array(101).fill(entry)),/100/);
nodes.get('#repoImportJson').value=JSON.stringify(entry);
context.previewRepositoryImport();
assert.equal(nodes.get('#repoRunImport').disabled,true);
assert.match(nodes.get('#repoImportPreview').innerHTML,/migration/);
state.grammarLibraryReady=true;
context.previewRepositoryImport();assert.equal(nodes.get('#repoRunImport').disabled,false);
const hostile=copy(entry);hostile.grammar_explanations[0].explanation='<img src=x onerror=alert(1)>';
conflictInputs=[{...node(),dataset:{repoConflict:'0'},checked:false}];
state.grammarGuides=[saved];nodes.get('#repoImportJson').value=JSON.stringify(hostile);context.previewRepositoryImport();
assert.equal(nodes.get('#repoRunImport').disabled,true);
assert.ok(!nodes.get('#repoImportPreview').innerHTML.includes('<img'));
conflictInputs[0].checked=true;conflictInputs[0].handlers.change();
assert.equal(nodes.get('#repoRunImport').disabled,false);
assert.equal(vm.runInContext('pendingRepositoryImport[0].guides[0].expected_content.meaning',context),explanation.meaning);
conflictInputs[0].checked=false;conflictInputs[0].handlers.change();assert.equal(nodes.get('#repoRunImport').disabled,true);
conflictInputs=[];
state.grammarLinks=[{repository_id:'sentence1',label:explanation.label,grammar_id:saved.id}];
const linked={...entry,id:'sentence1'};
assert.equal(context.repositoryGrammarGuide(explanation.label,linked).id,'guide1');
assert.equal(context.repositoryGrammarGuide(explanation.label,{...entry,id:'unlinked'}),undefined,'Never guess meaning for unlinked labels');
state.grammarLabel=explanation.label;
assert.match(context.repositoryGrammarMarkup(linked),/AI-generated · Unverified/);

(async()=>{
  state.grammarGuides=[];
  let rpcCalls=0,insertCalls=0,release;
  context.renderRepository=()=>{};
  context.db={rpc:async(name,args)=>{
    rpcCalls++;assert.equal(name,'import_repository_with_grammar');
    assert.equal(args.p_entries[0].guides[0].content.meaning,explanation.meaning);
    await new Promise(resolve=>release=resolve);
    return {data:{entries:[{...entry,id:'saved'}],guides:[saved],links:[]}};
  },from:()=>({insert:rows=>{insertCalls++;assert.ok(!('grammar_explanations' in rows[0]));return {select:async()=>({data:rows})};}})};
  nodes.get('#repoImportJson').value=JSON.stringify(entry);context.previewRepositoryImport();
  nodes.get('#repoImportJson').value+=' ';
  await context.runRepositoryImport();assert.equal(rpcCalls,0,'Stale JSON cannot import');
  context.previewRepositoryImport();
  const running=context.runRepositoryImport();await context.runRepositoryImport();
  assert.equal(rpcCalls,1,'Double click cannot submit twice');release();await running;
  assert.equal(state.entries[0].id,'saved');assert.equal(state.grammarGuides[0].id,'guide1');
  state.grammarLibraryReady=false;nodes.get('#repoImportJson').value=JSON.stringify({japanese:'日本語'});
  context.previewRepositoryImport();await context.runRepositoryImport();assert.equal(insertCalls,1,'Legacy import works before migration');
  state.grammarLibraryReady=true;nodes.get('#repoImportJson').value=JSON.stringify(entry);context.previewRepositoryImport();
  const before=state.entries.length;
  context.db.rpc=async()=>({error:{message:'Conflict'}});
  await context.runRepositoryImport();assert.equal(state.entries.length,before);assert.equal(nodes.get('#repoImportJson').disabled,false);
  context.bindRepositoryEvents(null);
  nodes.get('#repoImportJson').handlers.input();assert.equal(nodes.get('#repoRunImport').disabled,true);
  assert.equal(vm.runInContext('pendingRepositoryImport.length',context),0);
  context.db={from:table=>({select:()=>({eq:()=>{
    const response=table==='japanese_repository'?{data:[{id:'legacy-entry'}]}:table==='japanese_repository_revisions'?{data:[]}:{error:{message:'relation does not exist'}};
    return {...response,order:async()=>response};
  }})})};
  await context.loadRepositoryData(true);
  assert.equal(state.loaded,true);assert.equal(state.grammarLibraryReady,false);assert.equal(state.error,'');
  assert.equal(state.entries[0].id,'legacy-entry','Missing new tables do not hide the old repository');
  context.resetRepositorySession();assert.equal(state.grammarGuides.length,0);assert.equal(state.grammarLinks.length,0);
  console.log('PASS: enriched/legacy JSON, guide validation, senses, reuse, conflicts, escaping, stale preview, double submission, RPC failure and session reset.');
})().catch(error=>{console.error(error);process.exitCode=1;});
