const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const root=path.resolve(__dirname,'..');
const router=fs.readFileSync(path.join(root,'router.js'),'utf8');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');

assert.doesNotMatch(html,/grammar-guides\.js/,'Retired static grammar-guide bundle is not loaded');
assert.match(html,/repository\.js/);
assert.match(html,/repository-search-input\.js/);
assert.match(html,/router\.js/);

for(const route of [
  '/plan/week/',
  '/repository',
  '/grammar/',
  '/books/'
]){
  assert.ok(router.includes(route)||app.includes(route),`Current router/app contains ${route} handling`);
}

assert.match(
  router,
  /parts\[0\]==='dictionary'/,
  'Dictionary routes are parsed structurally'
);
assert.match(
  router,
  /query\('\/dictionary'/,
  'Dictionary URLs are generated by the router'
);
assert.doesNotMatch(
  router,
  /\['complete','pending','encountered'\]/,
  'Retired Pending/Complete grammar filters are not accepted from URLs'
);

assert.match(router,/pushState|replaceState/,'SPA history remains explicit');
assert.match(router,/popstate/,'Browser history navigation remains supported');
assert.match(app,/data-view="repository"|data-view=\\?"repository"/,'Repository stays in primary navigation/runtime');
assert.match(router,/Page unavailable/,'Invalid routes retain a safe unavailable state');

console.log('PASS: current SPA route contract and script loading; retired grammar-guides.js dependency is gone.');
